# SITE CONFIGURATION
title: DIGITAL HEALTH # your site title
author: Bernadette  # You :P
description: > # Meta description of Homepage
  Different Technological developments in the Health sector.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Bernadettenakazibwe.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Bernadette
  links: 
    
# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: ![alt text](https://www.eternalworks.com/hubfs/SaaSFiles/bigstock--D-Rendering-Of-Human-Brain-O-195737152.jpg#keepProtocol) #Main background image: use the path from /assets/img/ => This will output /assets/img/posts/slee![alt text](https://www.eternalworks.com/hubfs/SaaSFiles/bigstock--D-Rendering-Of-Human-Brain-O-195737152.jpg#keepProtocol)k_lg.jpg

email: bernadettenakazibwe@gmail.com  # email for form submission

twitter_username:  # replace with your_twitter_username or comment to remove link from footer
github_username: Bernadettenakazibwe  # replace with your_github_username or comment to remove link from footer
instagram_username:   # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: Bernadette # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
